In [2]:
import numpy as np

In [6]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)[None].T
y = x1 + x2
print(x1)
print(x2)
print(y)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0.]
 [1.]
 [2.]]
[[ 0.  1.  2.]
 [ 4.  5.  6.]
 [ 8.  9. 10.]]


In [14]:
template = np.array([
            [0, 0],
            [0, 1],
            [1, 0],
            [0, 1],
            [1, 0],
            [1, 1]])

xy = [5, 7]

moved = template + xy
print(moved)
print(moved.flatten())

[[5 7]
 [5 8]
 [6 7]
 [5 8]
 [6 7]
 [6 8]]
[5 7 5 8 6 7 5 8 6 7 6 8]
