In [24]:
import numpy as np

In [27]:
rgbo_map = np.zeros((3, 6, 4))
a = np.array([100, 100, 100, 255])

# print(np.repeat(a, 6, axis=0))

In [28]:
rgbo_map[0] = a
print(rgbo_map)

[[[100. 100. 100. 255.]
  [100. 100. 100. 255.]
  [100. 100. 100. 255.]
  [100. 100. 100. 255.]
  [100. 100. 100. 255.]
  [100. 100. 100. 255.]]

 [[  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]]

 [[  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]
  [  0.   0.   0.   0.]]]
