In [32]:
import numpy as np

In [33]:
a = np.array([
    [100, 100, 100, 255],
    [150, 150, 150, 255],
    [200, 200, 200, 255]
])

print(np.repeat(a, 2, axis=0))

[[100 100 100 255]
 [100 100 100 255]
 [150 150 150 255]
 [150 150 150 255]
 [200 200 200 255]
 [200 200 200 255]]


In [34]:
a = np.array([0,1,2])
b = np.array([1,1])
print(a[:2]+b)

[1 2]


In [37]:
rand_val = 2
for x in range(10):
    rnd = np.random.randint(-rand_val, rand_val, 3)
    floor_rgbo = np.array([20,  20,  20 , 255])
    floor_rgbo[:3] += rnd
    print(floor_rgbo)


[ 18  20  19 255]
[ 18  19  19 255]
[ 19  20  18 255]
[ 21  21  21 255]
[ 20  20  21 255]
[ 18  20  19 255]
[ 20  21  21 255]
[ 21  20  20 255]
[ 19  18  20 255]
[ 20  20  18 255]
